add config comment support and fix bug of GetInt
chubaofs/chubaofs pull request #1024
Opened 2020-11-17 11:52 UTC by xrefft

Signed-off-by: xrefft <cserxiao@qq.com>

**What this PR does / why we need it**:
Make chubaofs configuration file support comments, which might be useful for some ops behavior.
BTW, fixed the bug that "Config.GetInt()" cannot get the int value correctly. 
(Config.GetInt() have 0 usage in code. I believe this function will be deprecated in future).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes 

**Special notes for your reviewer**:
The form of the comment is as follows:
```conf
{
  "GetInt": 1234, # English Comment test
  "GetInt64": 5678, # 中文注释测试
  "GetFloat": 1234.5678, # Prueba de comentarios en español
  "GetString": "test string", # Deutscher Kommentartest
  "GetBool": true, 
  "GetBoolStr": "true",
  "GetStringSlice": [
    "test string in slice 1",
    "test string in slice 2" # in [ comment test
  ],
  "Quote": "in quote # test"
}
```
see [util/config/config_test](util/config/config_test)

**Release note**:

```release-note
```

2020-11-18 09:56 UTC, mervinkid commented
ACK and review in progress.

2020-11-18 10:12 UTC, mervinkid requested changes
The **JSON** encoding format itself does not support comments, adding comment support to JSON breaks the JSON format rules. 

So this pull request will not be accepted.

It is necessary for the configuration file to support comments, but it is recommended to adopt other solutions that do not break the format rules. 

Currently **YAML** and **TOML** formats both support comments.

I think that adding support for [**YAML**](https://yaml.org) or [**TOML**](https://toml.io/en/) format configuration files is a better solution to improve the readability of configuration files.

2020-11-18 12:05 UTC, xrefft commented
> The **JSON** encoding format itself does not support comments, adding comment support to **JSON** breaks the JSON format rules.
> 
> So this pull request will not be accepted.
> 
> It is necessary for the configuration file to support comments, but it is recommended to adopt other solutions that do not break the format rules.
> 
> Currently **YAML** and **TOML** formats both support comments.
> 
> I think that adding support for [**YAML**](https://yaml.org) or [**TOML**](https://toml.io/en/) format configuration files is a better solution to improve the readability of configuration files.

Well...I believe my work is just like JSMin, [as json creator Douglas Crockford advocated in 2012].(https://archive.vn/20150704102718/https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr#selection-655.0-655.17).

But I agree with you, is YAML better as config.

2020-11-24 14:43 UTC, mervinkid commented
ACK and review in progress.

2020-12-01 09:09 UTC, mervinkid commented
Please use `toml` or `yaml` instead of the current pull request solution.

2021-01-04 07:03 UTC, closed without merging